/* Generated by tools/generate_c99.py - DO NOT EDIT MANUALLY */
#ifndef EGGA_SUPERVISOR_ENVELOPE_DATA_H
#define EGGA_SUPERVISOR_ENVELOPE_DATA_H

#include <stdint.h>
#include <stdbool.h>

#define EGGA_N_SPEED 5
#define EGGA_N_MU 5
#define EGGA_N_TAU 8
#define EGGA_N_MASS 4
#define EGGA_N_CELLS 800

#define EGGA_N_KP 7
#define EGGA_N_KI 4
#define EGGA_N_KD 6
#define EGGA_N_KHEAD 7
#define EGGA_N_GAINS 1176
#define EGGA_MASK_WORDS 19

extern const float egga_speed_axis[EGGA_N_SPEED];
extern const float egga_mu_axis[EGGA_N_MU];
extern const float egga_tau_axis[EGGA_N_TAU];
extern const float egga_mass_axis[EGGA_N_MASS];

extern const float egga_kp_axis[EGGA_N_KP];
extern const float egga_ki_axis[EGGA_N_KI];
extern const float egga_kd_axis[EGGA_N_KD];
extern const float egga_khead_axis[EGGA_N_KHEAD];

extern const float egga_rate_limit[EGGA_N_SPEED][EGGA_N_MASS];
extern const uint64_t egga_envelope_masks[EGGA_N_CELLS][EGGA_MASK_WORDS];

#define EGGA_AY_FRACTION_K 0.6f
#define EGGA_GRAVITY 9.81f
#define EGGA_MIN_FEASIBLE_SPEED 5.0f

#endif /* EGGA_SUPERVISOR_ENVELOPE_DATA_H */
