from __future__ import annotations

import json

import numpy as np

from egga.config import REPO_ROOT

ENVELOPE_NPZ = REPO_ROOT / "experiments" / "envelope" / "envelope_v1.npz"
ACTOR_JSON = REPO_ROOT / "results" / "phase6" / "b5_best.json"
C_DIR = REPO_ROOT / "src" / "c"


def generate_actor_weights() -> None:
    with open(ACTOR_JSON, encoding="utf-8") as f:
        data = json.load(f)

    W1 = np.array(data["W1"], dtype=np.float32)
    b1 = np.array(data["b1"], dtype=np.float32)
    W2 = np.array(data["W2"], dtype=np.float32)
    b2 = np.array(data["b2"], dtype=np.float32)

    lines = [
        "/* Generated by tools/generate_c99.py - DO NOT EDIT MANUALLY */",
        "#ifndef EGGA_ACTOR_WEIGHTS_H",
        "#define EGGA_ACTOR_WEIGHTS_H",
        "",
        "#define EGGA_OBS_DIM 6",
        "#define EGGA_ACTOR_HIDDEN_DIM 8",
        "#define EGGA_ACT_DIM 4",
        "#define EGGA_ACTOR_PARAM_COUNT 92",
        "",
        "static const float EGGA_ACTOR_W1[8][6] = {",
    ]
    for row in W1:
        vals = ", ".join(f"{float(v):.9e}f" for v in row)
        lines.append(f"    {{{vals}}},")
    lines.append("};")
    lines.append("")

    vals_b1 = ", ".join(f"{float(v):.9e}f" for v in b1)
    lines.append(f"static const float EGGA_ACTOR_B1[8] = {{{vals_b1}}};")
    lines.append("")

    lines.append("static const float EGGA_ACTOR_W2[4][8] = {")
    for row in W2:
        vals = ", ".join(f"{float(v):.9e}f" for v in row)
        lines.append(f"    {{{vals}}},")
    lines.append("};")
    lines.append("")

    vals_b2 = ", ".join(f"{float(v):.9e}f" for v in b2)
    lines.append(f"static const float EGGA_ACTOR_B2[4] = {{{vals_b2}}};")
    lines.append("")
    lines.append("static const float EGGA_DELTA_K_BOUNDS[4] = {0.6f, 0.04f, 0.15f, 0.6f};")
    lines.append("static const float EGGA_REFERENCE_GAINS[4] = {1.6f, 0.0125f, 0.141f, 0.5041f};")
    lines.append("")
    lines.append("#endif /* EGGA_ACTOR_WEIGHTS_H */")
    lines.append("")

    out_file = C_DIR / "actor_weights.h"
    out_file.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {out_file}")


def generate_envelope_data() -> None:
    data = np.load(ENVELOPE_NPZ)
    speed_axis = data["speed_axis"].astype(np.float32)
    mu_axis = data["mu_axis"].astype(np.float32)
    tau_axis = data["tau_axis"].astype(np.float32)
    mass_axis = data["mass_axis"].astype(np.float32)

    kp_axis = data["kp_axis"].astype(np.float32)
    ki_axis = data["ki_axis"].astype(np.float32)
    kd_axis = data["kd_axis"].astype(np.float32)
    khead_axis = data["khead_axis"].astype(np.float32)

    rate_limit = data["rate_limit"].astype(np.float32)
    ver = data["verified"]  # shape (5, 5, 8, 4, 7, 4, 6, 7)
    flat_cells = ver.reshape(800, 1176)

    packed = np.zeros((800, 19), dtype=np.uint64)
    for c in range(800):
        for g in range(1176):
            if flat_cells[c, g]:
                packed[c, g // 64] |= np.uint64(1) << np.uint64(g % 64)

    # 1. Header file
    h_lines = [
        "/* Generated by tools/generate_c99.py - DO NOT EDIT MANUALLY */",
        "#ifndef EGGA_SUPERVISOR_ENVELOPE_DATA_H",
        "#define EGGA_SUPERVISOR_ENVELOPE_DATA_H",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "",
        "#define EGGA_N_SPEED 5",
        "#define EGGA_N_MU 5",
        "#define EGGA_N_TAU 8",
        "#define EGGA_N_MASS 4",
        "#define EGGA_N_CELLS 800",
        "",
        "#define EGGA_N_KP 7",
        "#define EGGA_N_KI 4",
        "#define EGGA_N_KD 6",
        "#define EGGA_N_KHEAD 7",
        "#define EGGA_N_GAINS 1176",
        "#define EGGA_MASK_WORDS 19",
        "",
        "extern const float egga_speed_axis[EGGA_N_SPEED];",
        "extern const float egga_mu_axis[EGGA_N_MU];",
        "extern const float egga_tau_axis[EGGA_N_TAU];",
        "extern const float egga_mass_axis[EGGA_N_MASS];",
        "",
        "extern const float egga_kp_axis[EGGA_N_KP];",
        "extern const float egga_ki_axis[EGGA_N_KI];",
        "extern const float egga_kd_axis[EGGA_N_KD];",
        "extern const float egga_khead_axis[EGGA_N_KHEAD];",
        "",
        "extern const float egga_rate_limit[EGGA_N_SPEED][EGGA_N_MASS];",
        "extern const uint64_t egga_envelope_masks[EGGA_N_CELLS][EGGA_MASK_WORDS];",
        "",
        "#define EGGA_AY_FRACTION_K 0.6f",
        "#define EGGA_GRAVITY 9.81f",
        "#define EGGA_MIN_FEASIBLE_SPEED 5.0f",
        "",
        "#endif /* EGGA_SUPERVISOR_ENVELOPE_DATA_H */",
        "",
    ]
    (C_DIR / "supervisor_envelope_data.h").write_text("\n".join(h_lines), encoding="utf-8")
    print(f"Generated {C_DIR / 'supervisor_envelope_data.h'}")

    # 2. Source file with constant arrays
    c_lines = [
        "/* Generated by tools/generate_c99.py - DO NOT EDIT MANUALLY */",
        '#include "supervisor_envelope_data.h"',
        "",
    ]

    def _arr_c(name: str, arr: np.ndarray) -> str:
        vals = ", ".join(f"{float(v):.6e}f" for v in arr)
        return f"const float {name}[{len(arr)}] = {{{vals}}};"

    c_lines.append(_arr_c("egga_speed_axis", speed_axis))
    c_lines.append(_arr_c("egga_mu_axis", mu_axis))
    c_lines.append(_arr_c("egga_tau_axis", tau_axis))
    c_lines.append(_arr_c("egga_mass_axis", mass_axis))
    c_lines.append("")
    c_lines.append(_arr_c("egga_kp_axis", kp_axis))
    c_lines.append(_arr_c("egga_ki_axis", ki_axis))
    c_lines.append(_arr_c("egga_kd_axis", kd_axis))
    c_lines.append(_arr_c("egga_khead_axis", khead_axis))
    c_lines.append("")

    c_lines.append("const float egga_rate_limit[EGGA_N_SPEED][EGGA_N_MASS] = {")
    for r in rate_limit:
        vals = ", ".join(f"{float(v):.6e}f" for v in r)
        c_lines.append(f"    {{{vals}}},")
    c_lines.append("};")
    c_lines.append("")

    c_lines.append("const uint64_t egga_envelope_masks[EGGA_N_CELLS][EGGA_MASK_WORDS] = {")
    for c in range(800):
        vals = ", ".join(f"0x{int(packed[c, w]):016X}ULL" for w in range(19))
        c_lines.append(f"    {{{vals}}},")
    c_lines.append("};")
    c_lines.append("")

    (C_DIR / "supervisor_envelope_data.c").write_text("\n".join(c_lines), encoding="utf-8")
    print(f"Generated {C_DIR / 'supervisor_envelope_data.c'}")


if __name__ == "__main__":
    C_DIR.mkdir(parents=True, exist_ok=True)
    generate_actor_weights()
    generate_envelope_data()
